# Generated by Django 4.1.7 on 2023-03-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Apple', 'Apple'), ('Orange', 'Orange'), ('Mango', 'Mango'), ('Banana', 'Banana')], max_length=10)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_item', models.CharField(choices=[('Apple', 'Apple'), ('Orange', 'Orange'), ('Mango', 'Mango'), ('Banana', 'Banana')], max_length=10)),
                ('available_quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
